USE [master]
GO

CREATE DATABASE [DB_SERVICE_PAYMENT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_SERVICE_PAYMENT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DB_SERVICE_PAYMENT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_SERVICE_PAYMENT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DB_SERVICE_PAYMENT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_SERVICE_PAYMENT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO